version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: "ts_node_jest"
    open-pull-requests-limit: 30
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: "ts_node_vitest"
    open-pull-requests-limit: 30
  - package-ecosystem: "bundler"
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: "ruby_rspec"
    open-pull-requests-limit: 30
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: "java_junit_maven"
    open-pull-requests-limit: 30
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: "java_junit_gradle"
    open-pull-requests-limit: 30
