name: debugger-examples

ghc-options: -Wall

dependencies:
 - base == 4.*

# library:
#   source-dirs: src
library:
  source-dirs: .

tests:
  spec:
    defaults: hspec/hspec@main
    dependencies:
      - base
      - hspec
      - debugger-examples
